spring.datasource.url=jdbc:postgresql://localhost:5432/financedb
spring.datasource.username=postgres
spring.datasource.password=Rishabh@05#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=rishabh
spring.security.user.password=rishabh123

jwt.secret-key=7ThunnMeJ96H14LpJ2QrZT1/q0wCLvxzJ9l5R5r6bkkG+gTEy7WpNkfSEKWdyv8jxk9iEZdF7Arx431ToFU4zQ==